### ISSUE TITLE
Make config for failtoban for clickhouse access

### ISSUE THREAD

**Issue by riderx** [Cap-go/terraform_clickhouse#4]
the goal is to prevent attacker to bruteforce clickhouse password.
So failtoban or any other tool is ok, the only requirement you should show in video the bruteforce test and block by the tool

**Comment by ayewo** [comment]
@riderx How about whitelisting access to the ClickHouse DB using `iptables`/ `nftables` firewall rules? Only the IP address range of your server or serverless vendor will be able to access ClickHouse remotely. Connections by other IP address will be dropped.

**Comment by ayewo** [comment]
At least based on how the password is generated, 
https://github.com/Cap-go/terraform_clickhouse/blob/f80196e5311b34e6c1f69a88b71ce26662dbbd64/main.tf#L12-L15
there's no way for an attacker to brute force the DB password.

**Comment by riderx** [comment]
I’m not sure the IP of serverless is a good strategy, especially the list of locations evolve a lot so it seems not very doable.

why generate a random password make it impossible to brute force ?

if the db doesn’t have fail to ban or any protection mesure it just need to tr long time

**Comment by ayewo** [comment]
> I’m not sure the IP of serverless is a good strategy, especially the list of locations evolve a lot so it seems not very doable.

I've not kept up with all the changes you've made to switch to ClickHouse hence the question. I asked because if you've added a server to the existing serverless architecture, then perhaps we might be able to whitelist IP addresses, but it sounds like that is not the case.

> why generate a random password make it impossible to brute force ?
> if the db doesn’t have fail to ban or any protection mesure it just need to tr long time

Agreed, though if the password is easily guessable then yes, it can be brute forced very quickly.

**Comment by WcaleNieWolny** [comment]
@ayewo Is fail2ban enabled with the current architecture or no? As is, without your changes
